[package]
name = "iced-sugiyama"
version = "0.1.0"
edition = "2024"

[features]
default = []
animated = ["dep:lyon_algorithms"]

[dependencies]
iced.workspace = true
lyon_algorithms = { workspace = true, optional = true }
rust-sugiyama.workspace = true
petgraph = "0.8"

[dev-dependencies]
fastrand = "2"

[workspace]
members = [
    "examples/*",
]

[workspace.package]
version = "0.1.0"
authors = ["Nick Senger"]
edition = "2024"
license = "MIT"
repository = "https://github.com/nicksenger/iced-sugiyama"
categories = ["gui"]
keywords = ["science", "gui", "ui", "graphics", "interface", "widgets", "dinosaurs"]
rust-version = "1.88"

[workspace.dependencies]
iced = { version = "0.13", features = ["advanced", "canvas", "lazy"] }
lyon_algorithms = "1"
rust-sugiyama = { path = "../rust-sugiyama" }
