[package]
name = "iced-sugiyama"
version = "0.1.0"
edition = "2024"

[dependencies]
iced.workspace = true
lyon_algorithms.workspace = true
rust_sugiyama.workspace = true
petgraph = "0.8"

[dev-dependencies]
fastrand = "2"
serde_json = "1"

[workspace]
members = [
    "examples/*",
    "core",
]

[workspace.package]
version = "0.1.0"
authors = ["Nick Senger"]
edition = "2024"
license = "MIT"
repository = "https://github.com/nicksenger/iced-sugiyama"
categories = ["gui"]
keywords = ["science", "gui", "ui", "graphics", "interface", "widgets", "dinosaurs"]
rust-version = "1.88"

[workspace.dependencies]
iced = { version = "0.14", features = ["advanced", "canvas", "lazy"] }
rust_sugiyama = { package = "iced-sugiyama-core", path = "./core" }
lyon_algorithms = "1"
