[package]
name = "moar"
description = "UI for getting moar"
version = "0.1.0"
authors = ["Nick Senger"]
edition = "2024"
publish = false

[dependencies]
fastrand = "2"
image = { version = "0.24", default-features = false, features = ["png"] }
iced.workspace = true
serde_json = "1"
rust_sugiyama.workspace = true
iced-sugiyama = { path = "../.." }
thiserror = "2"
